default:
  image: python:3.11
  tags:
    - docker

deploy-pages:
  stage: deploy
  script:
    - bash docs/build.sh
  pages:
    publish: docs/build
  artifacts:
    paths:
      - docs/build
  only:
    - docs-multiversion
