default:
  image: python:3.11
  tags:
    - docker

deploy-pages:
  stage: deploy
  variables:
    GIT_STRATEGY: clone  # use fresh clone of repository (avoiding any old branches)
    USE_DEV_BRANCH: "true"
  script:
    - bash docs/build.sh
  pages: true  # specifies that this is a Pages job
  publish: docs/build  # should be nested under "pages" property starting from GitLab 17.9
  artifacts:
    paths:
      - docs/build
  only:
    - dev
