default:
  image: python:3.11
  tags:
    - docker

stages:
  - build
  - deploy

build-pages:
  stage: build
  variables:
    GIT_STRATEGY: clone  # use fresh clone of repository (avoiding any old branches)
    USE_DEV_BRANCH: "true"
  script:
    - bash docs/build.sh
  pages: true  # specifies that this is a Pages job
  publish: docs/build  # should be nested under "pages" property starting from GitLab 17.9
  artifacts:
    paths:
      - docs/build
  only:
    - dev

deploy-production:
  stage: deploy
  variables:
    GIT_STRATEGY: clone  # use fresh clone of repository (avoiding any old branches)
    USE_DEV_BRANCH: "false"
    DOCUMENTATION_REPOSITORY: "$DOCUMENTATION_REPOSITORY"
    DOCUMENTATION_BRANCH: "master"
    DOCUMENTATION_LOCAL_REPO: "docs/production"
    DOCUMENTATION_SSH_PRIVATE_KEY: "$SSH_PRIVATE_KEY"
    DOCUMENTATION_GIT_USERNAME: "$GITLAB_USER_NAME"
    DOCUMENTATION_GIT_EMAIL: "$GITLAB_USER_EMAIL"
    DOCUMENTATION_ARTIFACTS_PATH: "docs/build"
    DOCUMENTATION_TARGET_PATH: "static/api/beamngpy"
  script:
    - bash docs/build.sh
    - bash docs/deploy_production.sh
  artifacts:
    paths:
      - docs/build
  only:
    - master
